version: 2
formats: []
python:
  install:
  - requirements: requirements.txt
build:
  os: ubuntu-lts-latest
  tools:
    python: latest
    nodejs: latest
  jobs:
    post_install:
    - npm install
mkdocs:
  configuration: mkdocs.yml
