version: 2
formats: []
python:
  install:
  - requirements: requirements.txt
build:
  os: ubuntu-22.04
  tools:
    python: "3"
  jobs:
    pre_create_environment:
    - echo "Command run at 'pre_create_environment' step"
    post_build:
    - echo "Command run at 'post_build' step"
    - echo `date`
  commands:
  - echo "Hello World" > _readthedocs/html/index.html
  - echo "Custom 404 page" > _readthedocs/html/404.html
mkdocs:
  configuration: mkdocs.yml
