version: 2
formats: []
python:
  install:
  - requirements: requirements.txt
build:
  os: ubuntu-22.04
  tools:
    python: "3"
    nodejs: "18"
  jobs:
    post_install:
    - npm install
    - npm install -g sass
mkdocs:
  configuration: mkdocs.yml
