# 目录
sass:
    style: compressed

# 读取处理
encoding: utf-8

# 过滤内容
show_drafts: null
limit_posts: 0
future: true
unpublished: false

# 转换
lsi: false
excerpt_separator: "\n\n"
incremental: false

# 开发用服务器
baseurl: "" # 不包括主机名
show_dir_listing: false

# 输出
permalink: /blog/:year-:month-:day:output_ext
timezone: Asia/Shanghai

defaults:
    - scope:
          path: ""
          type: posts
      values:
          layout: post
          style: post

liquid:
    error_mode: warn
    strict_filters: false
    strict_variables: false

# Markdown
markdown: kramdown
kramdown:
    auto_ids: true
    entity_output: as_input
    toc_levels: 1..6
    smart_quotes:
        - apos
        - apos
        - quot
        - quot
    input: GFM
    hard_wrap: true
    footnote_nr: 1
    show_warnings: true
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        guess_lang: false
    typographic_symbols:
        hellip: "..."
        mdash: "---"
        ndash: "--"
        laquo: "<<"
        raquo: ">>"
        laquo_space: "<< "
        raquo_space: " >>"

# 自定义变量
title: Ŝalenzo
url: "http://metsubojinrai.top"

source: _source
destination: _deploy
