# 目录
sass:
    style: compressed
# Site settings
title: Lorem Ipsum - Web Developer
description: "A blog about lorem ipsum ..."
baseurl: "/space-jekyll-template" # for test: remove string '/space-jekyll-template' to ''
url: "http://victorvoid.github.io/space-jekyll-template/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# 读取处理
encoding: utf-8
# User settings
username: lorem ipsum
user_title: Lorem Ipsum - FrontEnd
email: lorem.lorem@ipsum.com
twitter_username: loremipsum
github_username:  loremipsum
gplus_username:  loremipsum
linkedin_public_url: loremipsum # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: loremipsum
profile_picture: https://68.media.tumblr.com/93f384858e9273d5b980b418e2f2f4d5/tumblr_o5i2aybLJG1uapsfmo2_250.png

# 过滤内容
show_drafts: null
limit_posts: 0
future: true
unpublished: false

# 转换
lsi: false
excerpt_separator: "\n\n"
incremental: false

# 开发用服务器
baseurl: "" # 不包括主机名
show_dir_listing: false

# 输出
permalink: /blog/:year-:month-:day:output_ext
timezone: Asia/Shanghai

defaults:
    - scope:
          path: ""
          type: posts
      values:
          layout: post
          style: post
# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

liquid:
    error_mode: warn
    strict_filters: false
    strict_variables: false
# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Markdown
markdown: kramdown
kramdown:
    auto_ids: true
    entity_output: as_input
    toc_levels: 1..6
    smart_quotes:
        - apos
        - apos
        - quot
        - quot
    input: GFM
    hard_wrap: true
    footnote_nr: 1
    show_warnings: true
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        guess_lang: false
    typographic_symbols:
        hellip: "..."
        mdash: "---"
        ndash: "--"
        laquo: "<<"
        raquo: ">>"
        laquo_space: "<< "
        raquo_space: " >>"
# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/victorvoid
      new_tab: true
      key_trigger: g
    - title: twitter
      url: http://www.twitter.com/victorvoid
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# 自定义变量
title: Ŝalenzo
url: "http://metsubojinrai.top"
# projects in header index
projects:
  - name: fluany
    url: https://github.com/fluany/fluany
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara

source: _source
destination: _deploy
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
