site_name: Ŝalenzo
site_url: https://salenzo.readthedocs.io/
repo_url: https://github.com/Salenzo/salenzo.readthedocs.io
edit_uri_template: "blob/main/src/{path}"
nav:
- Home: index.md
- Post: post/index.md
- Tool: tool/index.md
- Game: game/index.md
- About: about.md
- Metsubō Jinrai: https://metsubojinrai.top/
theme:
  name: null
  custom_dir: mkdocs
docs_dir: src
site_dir: _site
hooks:
- hooks.py
plugins: []
use_directory_urls: false
markdown_extensions:
  nl2br: {}
  sane_lists: {}
  mdx_math:
    enable_dollar_delimiter: true
